# Copyright 2018 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FROM alpine:3.6
FROM centos:7

RUN mkdir -p /opt/app-root/src
# WORKDIR /opt/app-root/src
COPY requirements.txt /opt/app-root/src
WORKDIR /opt/app-root/src

# For some reason pip doesn't install incremental (a Twisted dependency) so do
# so manually. When done, remove unneeded packages for a smaller image.
RUN yum install -y python36 openssh-server gcc glibc-devel ca-certificates && \
    ssh-keygen -A && \
    echo -e "ClientAliveInterval 1\nGatewayPorts yes\nPermitEmptyPasswords yes\nPort 8022\nClientAliveCountMax 10\nPermitRootLogin yes\n" >> /etc/ssh/sshd_config && \
    chmod -R 770 /etc/ssh/ && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir incremental && \
    pip3 install --no-cache-dir -r requirements.txt

# Make a /usr/bin/python for sshuttle
# RUN ln -s /usr/bin/python3 /usr/bin/python

COPY forwarder.py /opt/app-root/src
COPY socks.py /opt/app-root/src
COPY . /opt/app-root/src

CMD /opt/app-root/src/run.sh

# Set up to run as the telepresence user (1000:0)
RUN cp /opt/app-root/src/run-unpriv.sh /opt/app-root/src/run.sh && \
    chmod -R g+r /etc/ssh && \
    chmod -R g+w /opt/app-root/src && \
    chmod 660 /etc/passwd
    # echo "telepresence::1000:0:Telepresence User:/opt/app-root/src:/bin/bash" >> /etc/passwd
USER 1001